### ISSUE TITLE
logPackage: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#157]
Revise this error:
- [x] Prevent the getPath utility from crashing or find out it happens
- [x] Prevent the ADMIN UI from sending logPackage calls without a valid ID. Check if the DNP exists and is running beforehand

ERROR Call to logPackage
```
TypeError: Cannot read property 'split' of undefined
    at dockerComposeName (/usr/src/app/src/utils/getPath.js:81:43)
    at dockerCompose (/usr/src/app/src/utils/getPath.js:63:5)
    at Object.dockerComposeSmart (/usr/src/app/src/utils/getPath.js:36:30)
    at logPackage (/usr/src/app/src/calls/logPackage.js:26:37)
    at Object.<anonymous> (/usr/src/app/src/index.js:27:25)
    at tryCatchResolve (/usr/src/app/node_modules/when/lib/apply.js:46:23)
    at callAndResolve (/usr/src/app/node_modules/when/lib/apply.js:30:12)
    at callAndResolveNext (/usr/src/app/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/usr/src/app/node_modules/when/lib/makePromise.js:856:7)
    at runContinuation3 (/usr/src/app/node_modules/when/lib/makePromise.js:814:4)
    at Fulfilled.fold (/usr/src/app/node_modules/when/lib/makePromise.js:588:4)
    at callAndResolve (/usr/src/app/node_modules/when/lib/apply.js:34:12)
    at callAndResolveNext (/usr/src/app/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/usr/src/app/node_modules/when/lib/makePromise.js:856:7)
    at runContinuation3 (/usr/src/app/node_modules/when/lib/makePromise.js:814:4)
    at Fulfilled.fold (/usr/src/app/node_modules/when/lib/makePromise.js:588:4)
    at callAndResolve (/usr/src/app/node_modules/when/lib/apply.js:34:12)
    at callAndResolveNext (/usr/src/app/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/usr/src/app/node_modules/when/lib/makePromise.js:856:7)
    at runContinuation3 (/usr/src/app/node_modules/when/lib/makePromise.js:814:4)
    at Fulfilled.fold (/usr/src/app/node_modules/when/lib/makePromise.js:588:4)
    at callAndResolve (/usr/src/app/node_modules/when/lib/apply.js:34:12)

kwargs = {
  "options": {
    "timestamps": false,
    "tail": 200
  }
}
```

**Comment by dapplion** [comment]
Released on https://github.com/dappnode/DNP_DAPPMANAGER/releases/tag/v0.2.1
