### ISSUE TITLE
UPnP throws an error when does not exist

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_DAPPMANAGER#188]
In environments where UPnP is not available, DAPPMANAGER throws an error, with a trace:

```
ERROR [.] [] : Error checking if UPnP device is available: Error: Command failed: docker run --rm --net=host vpn.dnp.dappnode.eth:0.2.0 upnpc -l 
No IGD UPnP Device found on the network !

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

This should be a warning, without a trace.

**Comment by dapplion** [comment]
- [ ] Change log level from error to warning
