### ISSUE TITLE
Errors when removing WIFI Volume 

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_DAPPMANAGER#214]
![image](https://user-images.githubusercontent.com/21328788/58249778-08d4b180-7d60-11e9-9376-86463e3d616e.png)

![image](https://user-images.githubusercontent.com/21328788/58249784-0d996580-7d60-11e9-9475-d341b538d06e.png)

```Error: Command failed: docker logs DAppNodeCore-wifi.dnp.dappnode.eth  --tail 200 2>&1

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

kwargs = {
  "id": "wifi.dnp.dappnode.eth",
  "options": {
    "timestamps": false,
    "tail": 200
  }
}````


```Error: Command failed: docker volume rm -f 
"docker volume rm" requires at least 1 argument.
See 'docker volume rm --help'.

Usage:  docker volume rm [OPTIONS] VOLUME [VOLUME...]

Remove one or more volumes

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

kwargs = {
  "id": "wifi.dnp.dappnode.eth"
}````

**Comment by vdo** [comment]
WIFI package has no named volumes, so the button of deleting volumes should be disabled.

**Comment by Shelpin** [comment]
Checked!
