### ISSUE TITLE
UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_DAPPMANAGER#301]
I've found this error on the dappmanager logs after restart the ethchain:

```
ERROR [modules/web3Setup] [] : Web3 connection error to ws://my.ethchain.dnp.dappnode.eth:8546: connection not open
(node:1) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:1:1)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
    at Eth.Contract.self.setProvider (/usr/src/app/node_modules/web3-eth/src/index.js:158:23)
```

And the AdminUI isn't able to get the DAppNodeStore packages.

@dapplion suggested that this line could be the reason:

https://github.com/dappnode/DNP_DAPPMANAGER/blob/7b2dae20f2230d0199d4a7b2ab2f46c777b33350/build/src/src/modules/web3Setup.ts#L22

**Comment by dapplion** [comment]
No longer using WebSocket connections
