### ISSUE TITLE
Typing error

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#307]
After installing Raiden
```
WARN [calls/listPackages] [] : Error appending dappmanager.dnp.dappnode.eth files: TypeError: envsArray.filter is not a function
    at Object.parseEnvironment (/usr/src/app/src/utils/dockerComposeParsers.js:42:10)
    at Object.readConfigFiles (/usr/src/app/src/utils/configFiles.js:36:48)
    at dnpList.map.dnp (/usr/src/app/src/calls/listPackages.js:46:65)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/usr/src/app/src/calls/listPackages.js:44:17)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/src/calls/listPackages.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_DAPPMANAGER/commit/fc53773fe8a0da366b512fc980131a7bb419ccd9
