### ISSUE TITLE
Alias migration removes container network configuration

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#651]
The [recently merged PR](https://github.com/dappnode/DNP_DAPPMANAGER/pull/648) removes the container network configuration when adding the alias for those containers already running

Approach: 
- [ ] Research dockerode and docker API documentation: inspect networks/ list networks / connect container to a network
- [ ] Store the network container configuration before disconnect the container
- [ ] Connect again the container back to the network with the stored network configuration

**Comment by pablomendezroyo** [comment]
#### Error in `migration.ts` when adding alias to container: vpn

**Current status: debugging**
**Posible source problems: **
- `migration.ts` is editing incorrectly the composes files
- Defining two networks in the same compose file, both uses same subnet: 172.33.0.0/16

**Notes**
- Deleting aliases in the compose-vpn.yml (edited after the migration process) allow to `compose-up` the service with no errors in networking configuration (`docker inspect` => network settings)

```
INFO  [modules/https-portal/migration:55] Added alias to running container DAppNodeCore-ipfs.dnp.dappnode.eth
WARN  [initializeDb:169] VPN DB not imported, vpndb.json missing.
INFO  [modules/https-portal/migration:55] Added alias to running container DAppNodeCore-bind.dnp.dappnode.eth
ERROR [modules/https-portal/migration:57] Error adding alias to container DAppNodeCore-vpn.dnp.dappnode.eth { Error: (HTTP code 500) server error - failed to add interface veth5d90f2a to sandbox: error setting interface "veth5d90f2a" IP to 172.33.1.4/16: cannot program address 172.33.1.4/16 in sandbox interface because it conflicts with existing route {Ifindex: 2 Dst: 172.33.8.0/22 Src: 172.33.8.1 Gw: <nil> Flags: [] Table: 254} 
    at /usr/src/app/webpack:/app/node_modules/docker-modem/lib/modem.js:301:1
    at getCause (/usr/src/app/webpack:/app/node_modules/docker-modem/lib/modem.js:331:1)
    at Modem.buildPayload (/usr/src/app/webpack:/app/node_modules/docker-modem/lib/modem.js:300:1)
    at IncomingMessage.<anonymous> (/usr/src/app/webpack:/app/node_modules/docker-modem/lib/modem.js:275:1)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  reason: 'server error',
  statusCode: 500,
  json:
   { message:
      'failed to add interface veth5d90f2a to sandbox: error setting interface "veth5d90f2a" IP to 172.33.1.4/16: cannot program address 172.33.1.4/16 in sandbox interface because it conflicts with existing route {Ifindex: 2 Dst: 172.33.8.0/22 Src: 172.33.8.1 Gw: <nil> Flags: [] Table: 254}' } }
      ```

**Comment by pablomendezroyo** [comment]
https://github.com/dappnode/DNP_DAPPMANAGER/pull/652 closes
