### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: res.status is not a function

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#781]
**Describe the bug**
I could see this error on the dappmanager logs, the source of the error in unknown. 

**Expected behaviour**

**Logs**

```
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 23)
(node:1) UnhandledPromiseRejectionWarning: TypeError: res.status is not a function
    at Object.<anonymous> (/usr/src/app/webpack:/src/api/utils.ts:29:13)
    at Generator.next (<anonymous>)
    at /usr/src/app/index.js:25643:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/index.js:25639:12)
    at /usr/src/app/webpack:/src/api/utils.ts:22:50
    at Array.<anonymous> (/usr/src/app/webpack:/src/api/utils.ts:63:5)
    at run (/usr/src/app/webpack:/app/node_modules/socket.io/lib/namespace.js:124:1)
    at /usr/src/app/webpack:/app/node_modules/socket.io/lib/namespace.js:132:1
    at _cookieSession (/usr/src/app/webpack:/app/node_modules/cookie-session/index.js:126:1)
    at Array.<anonymous> (/usr/src/app/webpack:/src/api/utils.ts:63:5)
    at run (/usr/src/app/webpack:/app/node_modules/socket.io/lib/namespace.js:124:1)
    at Namespace.run (/usr/src/app/webpack:/app/node_modules/socket.io/lib/namespace.js:136:1)
    at Namespace.add (/usr/src/app/webpack:/app/node_modules/socket.io/lib/namespace.js:164:1)
    at Client.doConnect (/usr/src/app/webpack:/app/node_modules/socket.io/lib/client.js:97:1)
    at Client.connect (/usr/src/app/webpack:/app/node_modules/socket.io/lib/client.js:66:1)
    at Server.onconnection (/usr/src/app/webpack:/app/node_modules/socket.io/lib/index.js:435:1)
    at Server.emit (events.js:314:20)
    at Server.handshake (/usr/src/app/webpack:/app/node_modules/engine.io/lib/server.js:338:1)
    at /usr/src/app/webpack:/app/node_modules/engine.io/lib/server.js:230:1
    at Server.checkRequest (/usr/src/app/webpack:/app/node_modules/socket.io/lib/index.js:76:1)
    at Server.verify (/usr/src/app/webpack:/app/node_modules/engine.io/lib/server.js:166:1)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 24)

(node:1) UnhandledPromiseRejectionWarning: TypeError: res.status is not a function
    at Object.<anonymous> (/usr/src/app/webpack:/src/api/utils.ts:29:13)
    at Generator.next (<anonymous>)
    at /usr/src/app/index.js:25643:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/index.js:25639:12)
    at /usr/src/app/webpack:/src/api/utils.ts:22:50
    at Array.<anonymous> (/usr/src/app/webpack:/src/api/utils.ts:63:5)
    at run (/usr/src/app/webpack:/app/node_modules/socket.io/lib/namespace.js:124:1)
    at /usr/src/app/webpack:/app/node_modules/socket.io/lib/namespace.js:132:1
    at _cookieSession (/usr/src/app/webpack:/app/node_modules/cookie-session/index.js:126:1)
    at Array.<anonymous> (/usr/src/app/webpack:/src/api/utils.ts:63:5)
    at run (/usr/src/app/webpack:/app/node_modules/socket.io/lib/namespace.js:124:1)
    at Namespace.run (/usr/src/app/webpack:/app/node_modules/socket.io/lib/namespace.js:136:1)
    at Namespace.add (/usr/src/app/webpack:/app/node_modules/socket.io/lib/namespace.js:164:1)
    at Client.doConnect (/usr/src/app/webpack:/app/node_modules/socket.io/lib/client.js:97:1)
    at Client.connect (/usr/src/app/webpack:/app/node_modules/socket.io/lib/client.js:66:1)
    at Server.onconnection (/usr/src/app/webpack:/app/node_modules/socket.io/lib/index.js:435:1)
    at Server.emit (events.js:314:20)
    at Server.handshake (/usr/src/app/webpack:/app/node_modules/engine.io/lib/server.js:338:1)
    at /usr/src/app/webpack:/app/node_modules/engine.io/lib/server.js:230:1
    at Server.checkRequest (/usr/src/app/webpack:/app/node_modules/socket.io/lib/index.js:76:1)
    at Server.verify (/usr/src/app/webpack:/app/node_modules/engine.io/lib/server.js:166:1)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 24)
```
**DAppNode version:**

core.dnp.dappnode.eth: 0.2.44
dappmanager.dnp.dappnode.eth: 0.2.39,

**Comment by dapplion** [comment]
The error happens here
https://github.com/dappnode/DNP_DAPPMANAGER/blob/6838be01fbd24e346c8c6e8c6a2a0940afcd939e/packages/dappmanager/src/api/utils.ts#L29

For this to break it means that a non-express request is getting piped through this functions.

**Comment by pablomendezroyo** [comment]
@tropicar I have not enough context, I was looking for this log in my dappmanager and I did not found. I cannot continue with it since I cannot reproduce the error

**Comment by pablomendezroyo** [comment]
Not enough context
