### ISSUE TITLE
Error when installing packages, failed docker load

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_DAPPMANAGER#85]
When installing packages from the admin panel, error shows up and installation is not complete.
Reproducible when installing both Telegram-MTProto and OTP-Web.
Logs:
```
INFO [.] [] : {"logId":"29415a5c-ec92-4ef8-a6e2-fd3c335bc43f","order":["telegram-mtpproto.dnp.dappnode.eth"]}
INFO [.] [] : {"logId":"29415a5c-ec92-4ef8-a6e2-fd3c335bc43f","pkg":"telegram-mtpproto.dnp.dappnode.eth","msg":"starting download..."}
INFO [.] [] : {"logId":"29415a5c-ec92-4ef8-a6e2-fd3c335bc43f","pkg":"telegram-mtpproto.dnp.dappnode.eth","msg":"loading image"}
ERROR [utils/shell] [] : SHELL JS ERROR, on command: docker load -i ./dnp_repo/telegram-mtpproto.dnp.dappnode.eth/telegram-mtpproto.dnp.dappnode.eth_0.0.1.tar.xz err: 
ERROR [.] [] : Call installPackage.dappmanager.dnp.dappnode.eth error: 
Stack: Error
    at shellExecSync (/usr/src/app/src/utils/shell.js:20:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Also looks like the timeout hardcoded in https://github.com/dappnode/DNP_DAPPMANAGER/blob/73c28b1f8dacf921b885c33ef3d43349d400a9b1/build/src/src/utils/shell.js#L4 is too low, or should not be defined.

Running the command manually, can take longer than 20s. One example:
```
/usr/src/app # time docker load -i ./dnp_repo/letsencrypt-nginx.dnp.dappnode.eth
/letsencrypt-nginx.dnp.dappnode.eth_0.0.4.tar.xz
Loaded image: letsencrypt-nginx.dnp.dappnode.eth:0.0.4
real	0m 25.98s
user	0m 0.19s
sys	0m 0.37s
/usr/src/app # echo $?
0
```

**Comment by vdo** [comment]
I tried increasing the timeout, deploying the app and now packages can be installed.

`const maxTime = 200*1000;`
