### ISSUE TITLE
Error removing HTTPS package when status stopped | crashed

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#910]
Not possible to remove the HTTPs package when the container is not running.

### To reproduce
1. Install HTTPs package
2. Stop HTTPs package
3. Remove HTTPs package

Behaviour not seen on non-system packages

### Error

Error:
```
Call to package remove

Error: (HTTP code 304) container already stopped -  
    at /usr/src/app/webpack:/node_modules/docker-modem/lib/modem.js:301:1
    at getCause (/usr/src/app/webpack:/node_modules/docker-modem/lib/modem.js:331:1)
    at Modem.buildPayload (/usr/src/app/webpack:/node_modules/docker-modem/lib/modem.js:300:1)
    at IncomingMessage.<anonymous> (/usr/src/app/webpack:/node_modules/docker-modem/lib/modem.js:275:1)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

{
  "dnpName": "https.dnp.dappnode.eth",
  "deleteVolumes": true
}
```

Source code:
https://github.com/dappnode/DNP_DAPPMANAGER/blob/a8c4dd819cee5e0834dc608c7c361cb7b60859a4/packages/dappmanager/src/calls/packageRemove.ts#L65

**Comment by pablomendezroyo** [comment]
This was affecting on every `packageRemove` with an already stopped container
